<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2024–2026: The Frontier – LLM Agents: A Survey (2022–2026)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-254a3ef50811769e7b813971395bbfc6.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-31e29ad2a3d1e7985534403fb9b8ee74.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-254a3ef50811769e7b813971395bbfc6.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">LLM Agents: A Survey (2022–2026)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./taxonomy.html"> 
<span class="menu-text">Taxonomy</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./timeline.html"> 
<span class="menu-text">Timeline</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./foundations.html"> 
<span class="menu-text">2022–2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./recent.html" aria-current="page"> 
<span class="menu-text">2024–2026</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-deep-dives" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Deep Dives</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-deep-dives">    
        <li>
    <a class="dropdown-item" href="./reasoning.html">
 <span class="dropdown-text">Reasoning &amp; Planning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./multiagent.html">
 <span class="dropdown-text">Multi-Agent Systems</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./memory-tools.html">
 <span class="dropdown-text">Memory, Tools &amp; Actions</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-topics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Topics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-topics">    
        <li>
    <a class="dropdown-item" href="./topics.html">
 <span class="dropdown-text">Topics Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./evaluation.html">
 <span class="dropdown-text">Evaluation &amp; Benchmarks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./safety.html">
 <span class="dropdown-text">Safety &amp; Alignment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./science-agents.html">
 <span class="dropdown-text">Science &amp; Research Agents</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./personalization.html">
 <span class="dropdown-text">Personalization &amp; Digital Twins</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./infrastructure.html">
 <span class="dropdown-text">Infrastructure &amp; Protocols</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./human-agent.html">
 <span class="dropdown-text">Human-Agent Interaction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./economics.html">
 <span class="dropdown-text">Agent Economics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./community.html"> 
<span class="menu-text">Community</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resources.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/johnplake/llm-agents-survey"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#coding-software-engineering-agents" id="toc-coding-software-engineering-agents" class="nav-link" data-scroll-target="#coding-software-engineering-agents">Coding &amp; Software Engineering Agents</a>
  <ul class="collapse">
  <li><a href="#swe-bench-the-scoreboard" id="toc-swe-bench-the-scoreboard" class="nav-link" data-scroll-target="#swe-bench-the-scoreboard">SWE-bench: The Scoreboard</a></li>
  <li><a href="#swe-agent-2024" id="toc-swe-agent-2024" class="nav-link" data-scroll-target="#swe-agent-2024">SWE-agent (2024)</a></li>
  <li><a href="#openhands-formerly-opendevin" id="toc-openhands-formerly-opendevin" class="nav-link" data-scroll-target="#openhands-formerly-opendevin">OpenHands (formerly OpenDevin)</a></li>
  <li><a href="#devin-cognition-ai-2024" id="toc-devin-cognition-ai-2024" class="nav-link" data-scroll-target="#devin-cognition-ai-2024">Devin (Cognition AI, 2024)</a></li>
  <li><a href="#claude-code-claude-agent-sdk-2025" id="toc-claude-code-claude-agent-sdk-2025" class="nav-link" data-scroll-target="#claude-code-claude-agent-sdk-2025">Claude Code → Claude Agent SDK (2025)</a></li>
  <li><a href="#github-copilot-coding-agent-may-2025" id="toc-github-copilot-coding-agent-may-2025" class="nav-link" data-scroll-target="#github-copilot-coding-agent-may-2025">GitHub Copilot Coding Agent (May 2025)</a></li>
  <li><a href="#agents-101-how-to-work-with-coding-agents-devin-cognition-ai" id="toc-agents-101-how-to-work-with-coding-agents-devin-cognition-ai" class="nav-link" data-scroll-target="#agents-101-how-to-work-with-coding-agents-devin-cognition-ai">Agents 101: How to Work with Coding Agents (Devin / Cognition AI)</a></li>
  <li><a href="#aider" id="toc-aider" class="nav-link" data-scroll-target="#aider">Aider</a></li>
  </ul></li>
  <li><a href="#major-agentic-products-2025" id="toc-major-agentic-products-2025" class="nav-link" data-scroll-target="#major-agentic-products-2025">Major Agentic Products (2025)</a>
  <ul class="collapse">
  <li><a href="#openai-operator-deep-research-chatgpt-agent" id="toc-openai-operator-deep-research-chatgpt-agent" class="nav-link" data-scroll-target="#openai-operator-deep-research-chatgpt-agent">OpenAI Operator + Deep Research + ChatGPT Agent</a></li>
  <li><a href="#anthropic-computer-use-oct-2024" id="toc-anthropic-computer-use-oct-2024" class="nav-link" data-scroll-target="#anthropic-computer-use-oct-2024">Anthropic Computer Use (Oct 2024)</a></li>
  <li><a href="#manus-ai-mar-2025-acquired-by-meta-dec-2025" id="toc-manus-ai-mar-2025-acquired-by-meta-dec-2025" class="nav-link" data-scroll-target="#manus-ai-mar-2025-acquired-by-meta-dec-2025">Manus AI (Mar 2025 → Acquired by Meta, Dec 2025)</a></li>
  <li><a href="#google-adk-gemini-agents" id="toc-google-adk-gemini-agents" class="nav-link" data-scroll-target="#google-adk-gemini-agents">Google: ADK + Gemini Agents</a></li>
  </ul></li>
  <li><a href="#new-protocols-the-infrastructure-layer" id="toc-new-protocols-the-infrastructure-layer" class="nav-link" data-scroll-target="#new-protocols-the-infrastructure-layer">New Protocols: The Infrastructure Layer</a>
  <ul class="collapse">
  <li><a href="#model-context-protocol-mcp-anthropic-nov-2024" id="toc-model-context-protocol-mcp-anthropic-nov-2024" class="nav-link" data-scroll-target="#model-context-protocol-mcp-anthropic-nov-2024">Model Context Protocol (MCP) — Anthropic, Nov 2024</a></li>
  <li><a href="#agent2agent-protocol-a2a-google-apr-2025" id="toc-agent2agent-protocol-a2a-google-apr-2025" class="nav-link" data-scroll-target="#agent2agent-protocol-a2a-google-apr-2025">Agent2Agent Protocol (A2A) — Google, Apr 2025</a></li>
  </ul></li>
  <li><a href="#framework-consolidation" id="toc-framework-consolidation" class="nav-link" data-scroll-target="#framework-consolidation">Framework Consolidation</a>
  <ul class="collapse">
  <li><a href="#microsoft-agent-framework-oct-2025" id="toc-microsoft-agent-framework-oct-2025" class="nav-link" data-scroll-target="#microsoft-agent-framework-oct-2025">Microsoft Agent Framework (Oct 2025)</a></li>
  <li><a href="#langgraph-v1.0-nov-2025" id="toc-langgraph-v1.0-nov-2025" class="nav-link" data-scroll-target="#langgraph-v1.0-nov-2025">LangGraph v1.0 (Nov 2025)</a></li>
  <li><a href="#goose-jan-2025" id="toc-goose-jan-2025" class="nav-link" data-scroll-target="#goose-jan-2025">Goose (Jan 2025)</a></li>
  </ul></li>
  <li><a href="#browser-computer-use-ecosystem" id="toc-browser-computer-use-ecosystem" class="nav-link" data-scroll-target="#browser-computer-use-ecosystem">Browser &amp; Computer Use Ecosystem</a>
  <ul class="collapse">
  <li><a href="#browser-use" id="toc-browser-use" class="nav-link" data-scroll-target="#browser-use">browser-use</a></li>
  <li><a href="#skyvern" id="toc-skyvern" class="nav-link" data-scroll-target="#skyvern">Skyvern</a></li>
  <li><a href="#stagehand-browserbase" id="toc-stagehand-browserbase" class="nav-link" data-scroll-target="#stagehand-browserbase">Stagehand (Browserbase)</a></li>
  </ul></li>
  <li><a href="#key-blog-posts-practitioner-resources-2024-2026" id="toc-key-blog-posts-practitioner-resources-2024-2026" class="nav-link" data-scroll-target="#key-blog-posts-practitioner-resources-2024-2026">Key Blog Posts &amp; Practitioner Resources (2024-2026)</a>
  <ul class="collapse">
  <li><a href="#anthropic-building-effective-agents-dec-2024" id="toc-anthropic-building-effective-agents-dec-2024" class="nav-link" data-scroll-target="#anthropic-building-effective-agents-dec-2024">Anthropic: Building Effective Agents (Dec 2024)</a></li>
  <li><a href="#google-cloud-lessons-from-2025-on-agents-and-trust-dec-2025" id="toc-google-cloud-lessons-from-2025-on-agents-and-trust-dec-2025" class="nav-link" data-scroll-target="#google-cloud-lessons-from-2025-on-agents-and-trust-dec-2025">Google Cloud: Lessons from 2025 on Agents and Trust (Dec 2025)</a></li>
  <li><a href="#agentic-ai-mcp-and-spec-driven-development-jan-2026" id="toc-agentic-ai-mcp-and-spec-driven-development-jan-2026" class="nav-link" data-scroll-target="#agentic-ai-mcp-and-spec-driven-development-jan-2026">Agentic AI, MCP, and Spec-Driven Development (Jan 2026)</a></li>
  <li><a href="#what-we-learned-from-a-year-of-building-with-llms-2024" id="toc-what-we-learned-from-a-year-of-building-with-llms-2024" class="nav-link" data-scroll-target="#what-we-learned-from-a-year-of-building-with-llms-2024">What We Learned from a Year of Building with LLMs (2024)</a></li>
  <li><a href="#ai-in-production-frameworks-protocols-and-what-actually-works-in-2026" id="toc-ai-in-production-frameworks-protocols-and-what-actually-works-in-2026" class="nav-link" data-scroll-target="#ai-in-production-frameworks-protocols-and-what-actually-works-in-2026">AI in Production: Frameworks, Protocols, and What Actually Works in 2026</a></li>
  </ul></li>
  <li><a href="#new-papers-2025-surveys-architecture-research" id="toc-new-papers-2025-surveys-architecture-research" class="nav-link" data-scroll-target="#new-papers-2025-surveys-architecture-research">New Papers: 2025 Surveys &amp; Architecture Research</a>
  <ul class="collapse">
  <li><a href="#agentic-ai-a-comprehensive-survey-of-architectures-applications-and-future-directions-oct-2025" id="toc-agentic-ai-a-comprehensive-survey-of-architectures-applications-and-future-directions-oct-2025" class="nav-link" data-scroll-target="#agentic-ai-a-comprehensive-survey-of-architectures-applications-and-future-directions-oct-2025">Agentic AI: A Comprehensive Survey of Architectures, Applications, and Future Directions (Oct 2025)</a></li>
  <li><a href="#agentic-ai-frameworks-architectures-protocols-and-design-challenges-aug-2025" id="toc-agentic-ai-frameworks-architectures-protocols-and-design-challenges-aug-2025" class="nav-link" data-scroll-target="#agentic-ai-frameworks-architectures-protocols-and-design-challenges-aug-2025">Agentic AI Frameworks: Architectures, Protocols, and Design Challenges (Aug 2025)</a></li>
  <li><a href="#architectures-for-building-agentic-ai-dec-2025" id="toc-architectures-for-building-agentic-ai-dec-2025" class="nav-link" data-scroll-target="#architectures-for-building-agentic-ai-dec-2025">Architectures for Building Agentic AI (Dec 2025)</a></li>
  <li><a href="#ai-agents-vs.-agentic-ai-a-conceptual-taxonomy-may-2025" id="toc-ai-agents-vs.-agentic-ai-a-conceptual-taxonomy-may-2025" class="nav-link" data-scroll-target="#ai-agents-vs.-agentic-ai-a-conceptual-taxonomy-may-2025">AI Agents vs.&nbsp;Agentic AI: A Conceptual Taxonomy (May 2025)</a></li>
  <li><a href="#towards-a-science-of-scaling-agent-systems-dec-2025" id="toc-towards-a-science-of-scaling-agent-systems-dec-2025" class="nav-link" data-scroll-target="#towards-a-science-of-scaling-agent-systems-dec-2025">Towards a Science of Scaling Agent Systems (Dec 2025)</a></li>
  <li><a href="#the-2025-ai-agent-index-feb-2026" id="toc-the-2025-ai-agent-index-feb-2026" class="nav-link" data-scroll-target="#the-2025-ai-agent-index-feb-2026">The 2025 AI Agent Index (Feb 2026)</a></li>
  <li><a href="#ai-agent-systems-architectures-applications-and-evaluation-jan-2026" id="toc-ai-agent-systems-architectures-applications-and-evaluation-jan-2026" class="nav-link" data-scroll-target="#ai-agent-systems-architectures-applications-and-evaluation-jan-2026">AI Agent Systems: Architectures, Applications, and Evaluation (Jan 2026)</a></li>
  </ul></li>
  <li><a href="#mit-ai-agent-index-2025" id="toc-mit-ai-agent-index-2025" class="nav-link" data-scroll-target="#mit-ai-agent-index-2025">MIT AI Agent Index (2025)</a></li>
  <li><a href="#metr-task-time-horizons-as-the-new-benchmark" id="toc-metr-task-time-horizons-as-the-new-benchmark" class="nav-link" data-scroll-target="#metr-task-time-horizons-as-the-new-benchmark">METR: Task Time Horizons as the New Benchmark</a></li>
  <li><a href="#openai-harness-engineering-long-horizon-codex-2025" id="toc-openai-harness-engineering-long-horizon-codex-2025" class="nav-link" data-scroll-target="#openai-harness-engineering-long-horizon-codex-2025">OpenAI Harness Engineering &amp; Long-Horizon Codex (2025)</a>
  <ul class="collapse">
  <li><a href="#openai-harness-engineering" id="toc-openai-harness-engineering" class="nav-link" data-scroll-target="#openai-harness-engineering">OpenAI Harness Engineering</a></li>
  <li><a href="#running-long-horizon-tasks-with-codex" id="toc-running-long-horizon-tasks-with-codex" class="nav-link" data-scroll-target="#running-long-horizon-tasks-with-codex">Running Long-Horizon Tasks with Codex</a></li>
  </ul></li>
  <li><a href="#from-vibe-coding-to-agentic-engineering" id="toc-from-vibe-coding-to-agentic-engineering" class="nav-link" data-scroll-target="#from-vibe-coding-to-agentic-engineering">From Vibe Coding to Agentic Engineering</a>
  <ul class="collapse">
  <li><a href="#glm-5-from-vibe-coding-to-agentic-engineering-2026" id="toc-glm-5-from-vibe-coding-to-agentic-engineering-2026" class="nav-link" data-scroll-target="#glm-5-from-vibe-coding-to-agentic-engineering-2026">GLM-5: From Vibe Coding to Agentic Engineering (2026)</a></li>
  </ul></li>
  <li><a href="#whats-next" id="toc-whats-next" class="nav-link" data-scroll-target="#whats-next">What’s Next</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a>
  <ul class="collapse">
  <li><a href="#papers-benchmarks" id="toc-papers-benchmarks" class="nav-link" data-scroll-target="#papers-benchmarks">Papers &amp; Benchmarks</a></li>
  <li><a href="#open-source-projects-frameworks" id="toc-open-source-projects-frameworks" class="nav-link" data-scroll-target="#open-source-projects-frameworks">Open-Source Projects &amp; Frameworks</a></li>
  <li><a href="#official-framework-protocol-documentation" id="toc-official-framework-protocol-documentation" class="nav-link" data-scroll-target="#official-framework-protocol-documentation">Official Framework &amp; Protocol Documentation</a></li>
  <li><a href="#key-blog-posts-practitioner-resources" id="toc-key-blog-posts-practitioner-resources" class="nav-link" data-scroll-target="#key-blog-posts-practitioner-resources">Key Blog Posts &amp; Practitioner Resources</a></li>
  <li><a href="#enterprise-products-evaluations" id="toc-enterprise-products-evaluations" class="nav-link" data-scroll-target="#enterprise-products-evaluations">Enterprise Products &amp; Evaluations</a></li>
  <li><a href="#measurement-research" id="toc-measurement-research" class="nav-link" data-scroll-target="#measurement-research">Measurement &amp; Research</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2024–2026: The Frontier</h1>
<p class="subtitle lead">Coding agents, agentic products, new protocols, and where the field is now</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>2024–2026 witnessed a fundamental shift: LLM agents moved from <strong>research prototypes to mainstream products</strong>. The year 2025 will be remembered as when reasoning models became agents, when browser automation went viral, and when the infrastructure for multi-agent systems matured into production-ready frameworks.</p>
<p>Key storylines:</p>
<ul>
<li><strong>Coding agents became the killer app</strong> — SWE-bench progress from ~12% (2024) to 77%+ (2025)</li>
<li><strong>Computer use went mass market</strong> — Anthropic Computer Use, OpenAI Operator, dozens of open-source tools</li>
<li><strong>Protocol wars</strong> — MCP (Anthropic, Nov 2024) and A2A (Google, Apr 2025) competed to become the standard</li>
<li><strong>Framework consolidation</strong> — Microsoft merged AutoGen + Semantic Kernel; LangGraph hit v1.0</li>
<li><strong>“2025 is the year of the agent”</strong> — became the defining claim of every AI company’s roadmap</li>
</ul>
<hr>
</section>
<section id="coding-software-engineering-agents" class="level2">
<h2 class="anchored" data-anchor-id="coding-software-engineering-agents">Coding &amp; Software Engineering Agents</h2>
<p>This became the most competitive sub-field of agent research, driven by clear benchmarks and commercial demand.</p>
<section id="swe-bench-the-scoreboard" class="level3">
<h3 class="anchored" data-anchor-id="swe-bench-the-scoreboard">SWE-bench: The Scoreboard</h3>
<p>SWE-bench (Jimenez et al., 2023) measures the ability of agents to resolve real GitHub issues. Progress has been stunning:</p>
<p><em>Note: SWE-bench Verified (500 tasks, human-validated) became the standard leaderboard from Aug 2024. Earlier entries used SWE-bench Full (2,294 tasks) or Lite (570 tasks).</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 25%">
<col style="width: 34%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Date</th>
<th>System</th>
<th>Benchmark</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>May 2024</td>
<td>SWE-agent + GPT-4 Turbo (Princeton)</td>
<td>Full</td>
<td>12.47%</td>
</tr>
<tr class="even">
<td>Mar 2024</td>
<td>Devin (Cognition AI)</td>
<td>Lite</td>
<td>13.86%</td>
</tr>
<tr class="odd">
<td>Late 2024</td>
<td>Claude 3.5 Sonnet + scaffolding</td>
<td>Verified</td>
<td>~49%</td>
</tr>
<tr class="even">
<td>Oct 2025</td>
<td>Claude Sonnet 4.5</td>
<td>Verified</td>
<td>77.2% (82.0% with parallel compute)</td>
</tr>
<tr class="odd">
<td>Nov 2025</td>
<td>Gemini 3 Pro + Live-SWE-agent</td>
<td>Verified</td>
<td><strong>77.4%</strong></td>
</tr>
</tbody>
</table>
<p>A separate harder benchmark, <strong>SWE-bench Pro</strong> (Scale Labs), tests generalization on never-before-seen private codebases. GPT-5 scores <strong>23.3%</strong> and Claude Opus 4.1 scores <strong>23.1%</strong> there (<a href="https://labs.scale.com/leaderboard/swe_bench_pro_public">Scale Labs leaderboard</a>) vs.&nbsp;70%+ on Verified, revealing substantial overfitting to public repos.</p>
<p><strong>Key takeaway:</strong> The progress is real but benchmarks are being saturated. Evaluation is moving to harder, less contaminated tasks.</p>
</section>
<section id="swe-agent-2024" class="level3">
<h3 class="anchored" data-anchor-id="swe-agent-2024">SWE-agent (2024)</h3>
<p><strong>Yang et al.&nbsp;(Princeton NLP)</strong> · <a href="https://arxiv.org/abs/2405.15793">arXiv:2405.15793</a></p>
<p>The benchmark-setting open-source coding agent. Uses Agent-Computer Interface (ACI) — a carefully designed shell environment for agents, with tools optimized for code understanding and editing. Achieved 12.5% on SWE-bench full at release (12.47% per the official leaderboard); seminal for the field.</p>
<ul>
<li><strong>GitHub:</strong> <a href="https://github.com/princeton-nlp/SWE-agent">princeton-nlp/SWE-agent</a> — 15k+ stars</li>
</ul>
</section>
<section id="openhands-formerly-opendevin" class="level3">
<h3 class="anchored" data-anchor-id="openhands-formerly-opendevin">OpenHands (formerly OpenDevin)</h3>
<p><strong>All-Hands AI</strong> · <a href="https://github.com/All-Hands-AI/OpenHands">github.com/All-Hands-AI/OpenHands</a> — 45k+ stars</p>
<p>The leading open-source autonomous software agent. Supports web browsing, file editing, shell execution, and code generation. Pluggable LLM backends (Claude, GPT-4, open models). Became the go-to open alternative to proprietary coding agents through 2025.</p>
</section>
<section id="devin-cognition-ai-2024" class="level3">
<h3 class="anchored" data-anchor-id="devin-cognition-ai-2024">Devin (Cognition AI, 2024)</h3>
<p><strong>Cognition AI</strong> · <a href="https://cognition.ai">cognition.ai</a></p>
<p>Launched March 2024 as “the first AI software engineer.” Raised significant venture funding and generated enormous press coverage. Uses a persistent developer environment (browser, terminal, editor). While its initial SWE-bench numbers were later revised, it validated commercial demand for autonomous coding.</p>
</section>
<section id="claude-code-claude-agent-sdk-2025" class="level3">
<h3 class="anchored" data-anchor-id="claude-code-claude-agent-sdk-2025">Claude Code → Claude Agent SDK (2025)</h3>
<p><strong>Anthropic</strong> · <a href="https://www.anthropic.com/engineering/building-agents-with-the-claude-agent-sdk">anthropic.com/engineering/building-agents-with-the-claude-agent-sdk</a> · <em>Sep 2025</em></p>
<p>Started as Claude Code — an agentic coding tool for the terminal. By September 2025, Anthropic renamed the underlying SDK to the <strong>Claude Agent SDK</strong>, recognizing it had become a general-purpose agent harness powering deep research, video creation, note-taking, and “almost all of our major agent loops.”</p>
<ul>
<li>In March 2026, Anthropic launched <strong>Code Review for Claude Code</strong> — parallel multi-agent code review dispatching specialized reviewer agents</li>
</ul>
</section>
<section id="github-copilot-coding-agent-may-2025" class="level3">
<h3 class="anchored" data-anchor-id="github-copilot-coding-agent-may-2025">GitHub Copilot Coding Agent (May 2025)</h3>
<p><strong>GitHub</strong> · <a href="https://github.blog/news-insights/product-news/github-copilot-meet-the-new-coding-agent/">github.blog</a></p>
<p>GitHub Copilot gained autonomous agent mode, integrating with IDEs (VS Code, Xcode, Eclipse, JetBrains, Visual Studio). Agent mode allows multi-step autonomous task execution within the GitHub ecosystem. Introduced <strong>GitHub Agent HQ</strong> at Universe 2025 (Oct 2025) — a unified workflow for orchestrating any agent.</p>
</section>
<section id="agents-101-how-to-work-with-coding-agents-devin-cognition-ai" class="level3">
<h3 class="anchored" data-anchor-id="agents-101-how-to-work-with-coding-agents-devin-cognition-ai">Agents 101: How to Work with Coding Agents (Devin / Cognition AI)</h3>
<p><strong>Cognition AI</strong> · <a href="https://devin.ai/agents101">devin.ai/agents101</a></p>
<p>Cognition’s practical guide for engineers integrating autonomous coding agents into their workflows — distilled from building Devin and observing thousands of users. The framing: <em>“A human paired with an AI assistant can achieve more than any AI alone… turning every engineer into an engineering manager.”</em></p>
<p>Six key principles:</p>
<ol type="1">
<li><strong>Say how you want things done, not just what</strong> — specify the approach and architecture upfront; don’t just state the goal</li>
<li><strong>Tell the agent where to start</strong> — point it to the right files, repos, and docs; minimize wasted exploration</li>
<li><strong>Practice defensive prompting</strong> — anticipate where a “junior intern” would get confused; preemptively clarify</li>
<li><strong>Give access to CI, tests, types, and linters</strong> — feedback loops via tools are “the magic” of agents; typed Python &gt; untyped; TypeScript &gt; JavaScript</li>
<li><strong>Leverage your expertise</strong> — human oversight of correctness remains non-negotiable; you own the code</li>
<li><strong>Delegate immediately</strong> — when a side task comes up, delegate to the agent and refocus; agents enable async multi-tasking</li>
</ol>
<p>Note: the guide references a growing ecosystem of similar agents (OpenAI Codex, Google Jules, Cursor, Claude Code) and integration patterns (Slack <span class="citation" data-cites="agent">@agent</span>, GitHub, Linear/Jira).</p>
</section>
<section id="aider" class="level3">
<h3 class="anchored" data-anchor-id="aider">Aider</h3>
<p><strong>Paul Gauthier</strong> · <a href="https://aider.chat">aider.chat</a> · <a href="https://github.com/paul-gauthier/aider">GitHub</a></p>
<p>The practical human-in-the-loop coding assistant. Works in the terminal, handles git diffs, supports Claude, GPT-4, and local models. Emphasizes transparency and control over full autonomy. Widely used and respected for its pragmatic design. Maintains a <strong>LLM coding leaderboard</strong> ranking models by real-world coding ability.</p>
<hr>
</section>
</section>
<section id="major-agentic-products-2025" class="level2">
<h2 class="anchored" data-anchor-id="major-agentic-products-2025">Major Agentic Products (2025)</h2>
<section id="openai-operator-deep-research-chatgpt-agent" class="level3">
<h3 class="anchored" data-anchor-id="openai-operator-deep-research-chatgpt-agent">OpenAI Operator + Deep Research + ChatGPT Agent</h3>
<p><strong>Operator</strong> launched January 2025 — an autonomous browser-use agent powered by the <strong>Computer-Using Agent (CUA)</strong> model combining GPT-4o vision with RL-trained reasoning. Could book reservations, fill forms, shop online.</p>
<p><strong>Deep Research</strong> launched February 2025 — powered by o3, conducts multi-step asynchronous research across the web, synthesizing findings into comprehensive reports. Hours of research in minutes.</p>
<p>In July 2025, these were merged into the <strong>ChatGPT Agent</strong> — a unified system combining Operator’s browser control, Deep Research’s information synthesis, and ChatGPT’s conversational ability. The first mass-market general-purpose agent.</p>
<ul>
<li><a href="https://openai.com/index/introducing-operator/">Introducing Operator</a> · <a href="https://openai.com/index/introducing-deep-research/">Deep Research</a> · <a href="https://openai.com/index/introducing-chatgpt-agent/">ChatGPT Agent</a></li>
</ul>
</section>
<section id="anthropic-computer-use-oct-2024" class="level3">
<h3 class="anchored" data-anchor-id="anthropic-computer-use-oct-2024">Anthropic Computer Use (Oct 2024)</h3>
<p><strong>Anthropic</strong></p>
<p>Launched October 2024, enabling Claude to directly control a computer: move the mouse, type, take screenshots, interpret the screen. First major LLM provider to offer this natively. Spawned a wave of open-source computer-use implementations.</p>
</section>
<section id="manus-ai-mar-2025-acquired-by-meta-dec-2025" class="level3">
<h3 class="anchored" data-anchor-id="manus-ai-mar-2025-acquired-by-meta-dec-2025">Manus AI (Mar 2025 → Acquired by Meta, Dec 2025)</h3>
<p><strong>Butterfly Effect / Monica.im (Singapore, Chinese-founded)</strong> · <a href="https://manus.im">manus.im</a> · <a href="https://arxiv.org/html/2505.02024v1">arXiv:2505.02024</a></p>
<p>Launched March 2025 as a general-purpose autonomous agent capable of completing complex real-world tasks with minimal human intervention — writing and deploying code, conducting research, managing files. Described as a “turning point” in AI development for its fully autonomous operation. Acquired by Meta in December 2025.</p>
</section>
<section id="google-adk-gemini-agents" class="level3">
<h3 class="anchored" data-anchor-id="google-adk-gemini-agents">Google: ADK + Gemini Agents</h3>
<p><strong>Google</strong> · <a href="https://google.github.io/adk-docs/">google.github.io/adk-docs</a> · <a href="https://github.com/google/adk-python">github.com/google/adk-python</a></p>
<p>Google’s <strong>Agent Development Kit (ADK)</strong> — an open-source Python framework for building, evaluating, and deploying AI agents. Model-agnostic but optimized for Gemini. Supports multi-agent workflows, tool integration, and deployment to Vertex AI. Introduced alongside Gemini 2.0’s native multimodal agent capabilities and Project Astra (real-time multimodal assistant).</p>
<hr>
</section>
</section>
<section id="new-protocols-the-infrastructure-layer" class="level2">
<h2 class="anchored" data-anchor-id="new-protocols-the-infrastructure-layer">New Protocols: The Infrastructure Layer</h2>
<p>2025 saw the emergence of <strong>open protocols</strong> for agent interoperability — a sign that the field was maturing beyond one-off integrations.</p>
<section id="model-context-protocol-mcp-anthropic-nov-2024" class="level3">
<h3 class="anchored" data-anchor-id="model-context-protocol-mcp-anthropic-nov-2024">Model Context Protocol (MCP) — Anthropic, Nov 2024</h3>
<p><strong>Anthropic</strong> · <a href="https://modelcontextprotocol.io">modelcontextprotocol.io</a></p>
<p>An open standard for connecting AI agents to external tools and data sources. Defines a client-server architecture: <strong>MCP servers</strong> expose tools/resources; agents connect as <strong>MCP clients</strong>. Quickly adopted across the industry — by early 2025, hundreds of MCP servers existed (GitHub, Slack, databases, filesystems, browsers).</p>
<p>The analogy: MCP is to AI agents what HTTP is to web browsers. OpenAI, Google, and all major framework builders endorsed it.</p>
<ul>
<li>Microsoft launched <strong>Playwright MCP</strong> (March 2025) — browser automation via MCP</li>
<li>Key blog: <a href="https://simonwillison.net/2024/Nov/25/model-context-protocol/">Simon Willison on MCP</a></li>
</ul>
</section>
<section id="agent2agent-protocol-a2a-google-apr-2025" class="level3">
<h3 class="anchored" data-anchor-id="agent2agent-protocol-a2a-google-apr-2025">Agent2Agent Protocol (A2A) — Google, Apr 2025</h3>
<p><strong>Google</strong> · <a href="https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/">developers.googleblog.com</a> · Donated to Linux Foundation Jun 2025</p>
<p>Announced April 2025 as a complement to MCP. While MCP handles agent-to-tool connections, <strong>A2A handles agent-to-agent communication</strong> across different vendors and frameworks. Donated to the Linux Foundation in June 2025 for neutral governance.</p>
<ul>
<li>Enables: cross-vendor agent delegation, trusted multi-agent pipelines, interoperability at scale</li>
</ul>
<hr>
</section>
</section>
<section id="framework-consolidation" class="level2">
<h2 class="anchored" data-anchor-id="framework-consolidation">Framework Consolidation</h2>
<section id="microsoft-agent-framework-oct-2025" class="level3">
<h3 class="anchored" data-anchor-id="microsoft-agent-framework-oct-2025">Microsoft Agent Framework (Oct 2025)</h3>
<p><strong>Microsoft</strong> · <a href="https://azure.microsoft.com/en-us/blog/introducing-microsoft-agent-framework/">azure.microsoft.com/blog/introducing-microsoft-agent-framework</a></p>
<p>Microsoft merged AutoGen (research multi-agent framework) and Semantic Kernel (enterprise SDK) into a single <strong>Microsoft Agent Framework</strong> — public preview October 2025, broader announcement December 2025, GA Q1 2026. Supports Python and .NET. Represents Microsoft’s bet on production-ready agentic AI for enterprise.</p>
</section>
<section id="langgraph-v1.0-nov-2025" class="level3">
<h3 class="anchored" data-anchor-id="langgraph-v1.0-nov-2025">LangGraph v1.0 (Nov 2025)</h3>
<p><strong>LangChain</strong> · <a href="https://github.com/langchain-ai/langgraph">github.com/langchain-ai/langgraph</a></p>
<p>LangGraph hit production-ready v1.0 in November 2025, becoming the dominant framework for complex stateful agent workflows in production. Used by Klarna, Replit, Elastic, and many others. Positioned as the “right tool” for agents needing fine-grained control over state and flow.</p>
</section>
<section id="goose-jan-2025" class="level3">
<h3 class="anchored" data-anchor-id="goose-jan-2025">Goose (Jan 2025)</h3>
<p><strong>Block (Jack Dorsey’s company)</strong> · <a href="https://github.com/block/goose">github.com/block/goose</a></p>
<p>Open-source, extensible AI agent that goes beyond code suggestions — installs, executes, edits, and tests with any LLM. Launched January 28, 2025. Popular in open-source circles for its extensibility and independence from proprietary ecosystems.</p>
<hr>
</section>
</section>
<section id="browser-computer-use-ecosystem" class="level2">
<h2 class="anchored" data-anchor-id="browser-computer-use-ecosystem">Browser &amp; Computer Use Ecosystem</h2>
<section id="browser-use" class="level3">
<h3 class="anchored" data-anchor-id="browser-use">browser-use</h3>
<p><strong><a href="https://github.com/browser-use/browser-use">github.com/browser-use/browser-use</a></strong> — 78,000+ stars</p>
<p>The #1 open-source browser automation platform. Makes websites accessible for AI agents, combining LLMs with visual recognition for real-time browser control. Exploded in 2025 following Anthropic Computer Use’s release, providing an open-source implementation for any model.</p>
</section>
<section id="skyvern" class="level3">
<h3 class="anchored" data-anchor-id="skyvern">Skyvern</h3>
<p><strong><a href="https://github.com/Skyvern-AI/skyvern">github.com/Skyvern-AI/skyvern</a></strong></p>
<p>AI agent for browser workflows using computer vision and LLMs — no CSS selectors or DOM knowledge needed. Visual workflow builder. Inspired by BabyAGI/AutoGPT but grounded in visual understanding.</p>
</section>
<section id="stagehand-browserbase" class="level3">
<h3 class="anchored" data-anchor-id="stagehand-browserbase">Stagehand (Browserbase)</h3>
<p>TypeScript-first browser automation framework for AI agents. Pairs well with browser-use (Python). Strong developer adoption in 2025.</p>
<hr>
</section>
</section>
<section id="key-blog-posts-practitioner-resources-2024-2026" class="level2">
<h2 class="anchored" data-anchor-id="key-blog-posts-practitioner-resources-2024-2026">Key Blog Posts &amp; Practitioner Resources (2024-2026)</h2>
<section id="anthropic-building-effective-agents-dec-2024" class="level3">
<h3 class="anchored" data-anchor-id="anthropic-building-effective-agents-dec-2024">Anthropic: Building Effective Agents (Dec 2024)</h3>
<p><strong>Erik Schluntz &amp; Barry Zhang (Anthropic)</strong> · <a href="https://www.anthropic.com/research/building-effective-agents">anthropic.com/research/building-effective-agents</a></p>
<p>The most practical and widely-cited 2024 post on agent design. Defines the crucial distinction:</p>
<blockquote class="blockquote">
<p><strong>Workflows</strong> = multiple LLMs orchestrated with pre-defined patterns<br>
<strong>Agents</strong> = LLMs that dynamically direct their own processes and tool usage</p>
</blockquote>
<p>Describes 5 core workflow patterns (prompt chaining, routing, parallelization, orchestrator-workers, evaluator-optimizer) and when to build truly autonomous agents vs.&nbsp;structured workflows. Essential reading.</p>
<ul>
<li><a href="https://simonwillison.net/2024/Dec/20/building-effective-agents/">Simon Willison’s writeup</a></li>
<li><a href="https://github.com/anthropics/anthropic-cookbook/tree/main/patterns/agents">Reference implementations</a></li>
</ul>
</section>
<section id="google-cloud-lessons-from-2025-on-agents-and-trust-dec-2025" class="level3">
<h3 class="anchored" data-anchor-id="google-cloud-lessons-from-2025-on-agents-and-trust-dec-2025">Google Cloud: Lessons from 2025 on Agents and Trust (Dec 2025)</h3>
<p><strong>Google Cloud CTO Office</strong> · <a href="https://cloud.google.com/transform/ai-grew-up-and-got-a-job-lessons-from-2025-on-agents-and-trust">cloud.google.com</a></p>
<p>Retrospective from Google’s enterprise deployments. Key insight: agents need <strong>“agent undo stacks”</strong> — idempotent tools and checkpointing that trigger safe rollbacks on failure. “AI grew up and got a job in 2025.”</p>
</section>
<section id="agentic-ai-mcp-and-spec-driven-development-jan-2026" class="level3">
<h3 class="anchored" data-anchor-id="agentic-ai-mcp-and-spec-driven-development-jan-2026">Agentic AI, MCP, and Spec-Driven Development (Jan 2026)</h3>
<p><strong>GitHub Blog</strong> · <a href="https://github.blog/developer-skills/agentic-ai-mcp-and-spec-driven-development-top-blog-posts-of-2025/">github.blog</a></p>
<p>GitHub’s summary of the most-read technical content of 2025. The top themes: agentic coding, MCP adoption, and spec-driven development (writing <code>AGENTS.md</code> files to guide coding agents).</p>
</section>
<section id="what-we-learned-from-a-year-of-building-with-llms-2024" class="level3">
<h3 class="anchored" data-anchor-id="what-we-learned-from-a-year-of-building-with-llms-2024">What We Learned from a Year of Building with LLMs (2024)</h3>
<p><strong>Eugene Yan, Bryan Bischof, Charles Frye, Hamel Husain et al.</strong> · <a href="https://applied-llms.org">applied-llms.org</a></p>
<p>Practitioner wisdom from engineers who shipped production LLM systems. Heavy on agent reliability, evals, and avoiding common failure modes. Widely cited as the most actionable guide of 2024.</p>
</section>
<section id="ai-in-production-frameworks-protocols-and-what-actually-works-in-2026" class="level3">
<h3 class="anchored" data-anchor-id="ai-in-production-frameworks-protocols-and-what-actually-works-in-2026">AI in Production: Frameworks, Protocols, and What Actually Works in 2026</h3>
<p><strong>47 Billion</strong> · <a href="https://47billion.com/blog/ai-agents-in-production-frameworks-protocols-and-what-actually-works-in-2026/">47billion.com</a></p>
<p>Four months of hands-on production building. Verdict: “the agent landscape in 2025 is simultaneously more capable and more fragile than the marketing suggests.”</p>
<hr>
</section>
</section>
<section id="new-papers-2025-surveys-architecture-research" class="level2">
<h2 class="anchored" data-anchor-id="new-papers-2025-surveys-architecture-research">New Papers: 2025 Surveys &amp; Architecture Research</h2>
<section id="agentic-ai-a-comprehensive-survey-of-architectures-applications-and-future-directions-oct-2025" class="level3">
<h3 class="anchored" data-anchor-id="agentic-ai-a-comprehensive-survey-of-architectures-applications-and-future-directions-oct-2025">Agentic AI: A Comprehensive Survey of Architectures, Applications, and Future Directions (Oct 2025)</h3>
<p><strong>Abou Ali &amp; Dornaika</strong> · <a href="https://arxiv.org/abs/2510.25445">arXiv:2510.25445</a></p>
<p>End-to-end survey covering January 2018–March 2025. Covers classical symbolic and modern LLM-orchestrated frameworks.</p>
</section>
<section id="agentic-ai-frameworks-architectures-protocols-and-design-challenges-aug-2025" class="level3">
<h3 class="anchored" data-anchor-id="agentic-ai-frameworks-architectures-protocols-and-design-challenges-aug-2025">Agentic AI Frameworks: Architectures, Protocols, and Design Challenges (Aug 2025)</h3>
<p><strong>Derouiche et al.</strong> · <a href="https://arxiv.org/abs/2508.10146">arXiv:2508.10146</a></p>
<p>Focused survey on the architectural and protocol layer — MCP, A2A, orchestration patterns.</p>
</section>
<section id="architectures-for-building-agentic-ai-dec-2025" class="level3">
<h3 class="anchored" data-anchor-id="architectures-for-building-agentic-ai-dec-2025">Architectures for Building Agentic AI (Dec 2025)</h3>
<p><a href="https://arxiv.org/abs/2512.09458">arXiv:2512.09458</a></p>
<p>Proposes a practical taxonomy: tool-using agents, memory-augmented agents, planning/self-improvement agents, multi-agent systems, and embodied/web agents. Analyzes how each reshapes system design.</p>
</section>
<section id="ai-agents-vs.-agentic-ai-a-conceptual-taxonomy-may-2025" class="level3">
<h3 class="anchored" data-anchor-id="ai-agents-vs.-agentic-ai-a-conceptual-taxonomy-may-2025">AI Agents vs.&nbsp;Agentic AI: A Conceptual Taxonomy (May 2025)</h3>
<p><a href="https://arxiv.org/abs/2505.10468">arXiv:2505.10468</a></p>
<p>Distinguishes <em>AI agents</em> (single-purpose, reactive) from <em>Agentic AI</em> (multi-agent collaboration, dynamic decomposition, persistent memory, coordinated autonomy). Useful conceptual clarification.</p>
</section>
<section id="towards-a-science-of-scaling-agent-systems-dec-2025" class="level3">
<h3 class="anchored" data-anchor-id="towards-a-science-of-scaling-agent-systems-dec-2025">Towards a Science of Scaling Agent Systems (Dec 2025)</h3>
<p><strong>Kim et al.</strong> · <a href="https://arxiv.org/abs/2512.08296">arXiv:2512.08296</a></p>
<p>Examines how agent system performance scales with the number of agents, compute, and interaction patterns.</p>
</section>
<section id="the-2025-ai-agent-index-feb-2026" class="level3">
<h3 class="anchored" data-anchor-id="the-2025-ai-agent-index-feb-2026">The 2025 AI Agent Index (Feb 2026)</h3>
<p><a href="https://arxiv.org/html/2602.17753v1">arXiv:2602.17753</a></p>
<p>Documents technical and safety features of deployed agentic AI systems across product overview, company accountability, technical capabilities, autonomy &amp; control, ecosystem interaction, and safety evaluation.</p>
</section>
<section id="ai-agent-systems-architectures-applications-and-evaluation-jan-2026" class="level3">
<h3 class="anchored" data-anchor-id="ai-agent-systems-architectures-applications-and-evaluation-jan-2026">AI Agent Systems: Architectures, Applications, and Evaluation (Jan 2026)</h3>
<p><a href="https://arxiv.org/html/2601.01743v1">arXiv:2601.01743</a></p>
<p>Synthesizes emerging agent architectures for reasoning, planning, tool use, and deployment. Analyzes system-level trade-offs: autonomy vs.&nbsp;controllability, latency vs.&nbsp;reliability, capability vs.&nbsp;safety.</p>
<hr>
</section>
</section>
<section id="mit-ai-agent-index-2025" class="level2">
<h2 class="anchored" data-anchor-id="mit-ai-agent-index-2025">MIT AI Agent Index (2025)</h2>
<p><strong>MIT</strong> · <a href="https://aiagentindex.mit.edu">aiagentindex.mit.edu</a></p>
<p>Systematic evaluation of <strong>30 prominent AI agents</strong> based on publicly available information. Documents origins, design, capabilities, ecosystem, and safety features. Key findings:</p>
<ul>
<li><strong>24/30 agents</strong> were released or received major agentic updates in 2024-2025</li>
<li><strong>Autonomy split:</strong> Chat agents at Level 1-3; browser agents at Level 4-5; enterprise agents from Level 1-2 (design) to Level 3-5 (deployment)</li>
<li><strong>Transparency gap:</strong> Of 13 frontier-autonomy agents, only 4 disclose any agentic safety evaluations. Developers share far more about capabilities than safety.</li>
<li><strong>Foundation model concentration:</strong> Nearly all depend on GPT, Claude, or Gemini — structural ecosystem risk</li>
<li><strong>No web conduct standards:</strong> Some agents explicitly designed to bypass anti-bot protections</li>
<li><strong>Geographic divergence:</strong> 21/30 US-based, 5/30 Chinese, markedly different safety frameworks</li>
</ul>
<p>Companion paper: <a href="https://arxiv.org/html/2602.17753v1">arXiv:2602.17753</a></p>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Safety in 2025-2026
</div>
</div>
<div class="callout-body-container callout-body">
<p>Safety — prompt injection, trust hierarchies, reversibility, the transparency gap — became a first-class concern as agents took real-world actions. Full coverage in <a href="./safety.html">Safety &amp; Alignment →</a></p>
</div>
</div>
<hr>
</section>
<section id="metr-task-time-horizons-as-the-new-benchmark" class="level2">
<h2 class="anchored" data-anchor-id="metr-task-time-horizons-as-the-new-benchmark">METR: Task Time Horizons as the New Benchmark</h2>
<p><strong>METR (Model Evaluation &amp; Threat Research)</strong> · <a href="https://metr.org/time-horizons/">metr.org/time-horizons</a></p>
<p>METR proposed measuring agents not by task accuracy but by <strong>task time horizon</strong> — the longest task an agent can complete with 50% reliability. This reframing captures something accuracy-based benchmarks miss: can agents sustain coherent action over minutes, hours, or days?</p>
<p><strong>Key findings (March 2025):</strong> - Claude 3.7 Sonnet: ~50 minutes time horizon <em>(50%-task-completion time horizon, per arXiv:2503.14499)</em> - GPT-5 (later 2025): ~2 hours 17 minutes - The time horizon has been <strong>doubling approximately every 7 months</strong> since 2019 - Extrapolation: agents capable of multi-day tasks within a few years</p>
<p>This metric directly maps to real-world utility. A 1-hour agent can do a coding task or research summary. A 24-hour agent could run a full experiment pipeline or manage a complex project.</p>
<p>See <a href="./science-agents.html#metr-measuring-ai-ability-to-complete-long-tasks-2025">Science &amp; Research Agents →</a> for more.</p>
<hr>
</section>
<section id="openai-harness-engineering-long-horizon-codex-2025" class="level2">
<h2 class="anchored" data-anchor-id="openai-harness-engineering-long-horizon-codex-2025">OpenAI Harness Engineering &amp; Long-Horizon Codex (2025)</h2>
<section id="openai-harness-engineering" class="level3">
<h3 class="anchored" data-anchor-id="openai-harness-engineering">OpenAI Harness Engineering</h3>
<p><strong>OpenAI</strong> · <a href="https://openai.com/index/harness-engineering/">openai.com/index/harness-engineering</a></p>
<p>OpenAI’s own internal experience with agentic software development. A team of 3 (growing to 7) engineers built a product with <strong>zero manually-written lines of code</strong>, over 1M+ lines of generated code, in ~5 months — with agents handling architecture, implementation, testing, and PR review.</p>
<p>Documents the workflow, failure modes, and lessons learned from living at the frontier of AI-assisted development. Key insight: at this level, the human’s job shifts from writing code to writing specs and reviewing agent outputs.</p>
</section>
<section id="running-long-horizon-tasks-with-codex" class="level3">
<h3 class="anchored" data-anchor-id="running-long-horizon-tasks-with-codex">Running Long-Horizon Tasks with Codex</h3>
<p><strong>OpenAI</strong> · <a href="https://developers.openai.com/blog/run-long-horizon-tasks-with-codex">developers.openai.com/blog/run-long-horizon-tasks-with-codex</a></p>
<p>Guidance on using OpenAI Codex for extended, multi-step software tasks. Covers context management, checkpointing, failure recovery, and task decomposition for tasks that span hours rather than minutes.</p>
<hr>
</section>
</section>
<section id="from-vibe-coding-to-agentic-engineering" class="level2">
<h2 class="anchored" data-anchor-id="from-vibe-coding-to-agentic-engineering">From Vibe Coding to Agentic Engineering</h2>
<section id="glm-5-from-vibe-coding-to-agentic-engineering-2026" class="level3">
<h3 class="anchored" data-anchor-id="glm-5-from-vibe-coding-to-agentic-engineering-2026">GLM-5: From Vibe Coding to Agentic Engineering (2026)</h3>
<p><strong>GLM-5-Team (Zhipu AI &amp; Tsinghua University)</strong> · <a href="https://arxiv.org/abs/2602.15763">arXiv:2602.15763</a></p>
<p>The GLM team (China’s Zhipu AI) traces the transition from informal prompt-based “vibe coding” to systematic <strong>agentic software engineering</strong> — with structured verification loops, multi-agent coordination, and principled task decomposition. Their GLM series is competitive with international frontier models on coding benchmarks, making this a significant non-Western perspective on the agentic coding frontier.</p>
<hr>
</section>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">What’s Next</h2>
<p>The open questions for 2026 and beyond:</p>
<ol type="1">
<li><strong>Long-horizon reliability</strong> — agents still fail on tasks requiring 100+ sequential steps</li>
<li><strong>Trust &amp; verification</strong> — how do you audit what an autonomous agent did?</li>
<li><strong>Cost</strong> — complex agent workflows burn through API credits fast</li>
<li><strong>Benchmark saturation</strong> — as SWE-bench fills up, what’s the next hard benchmark?</li>
<li><strong>Agent interoperability at scale</strong> — MCP + A2A adoption race</li>
<li><strong>Safety for real-world deployment</strong> — reversibility, sandboxing, human oversight patterns</li>
</ol>
<hr>
<hr>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<section id="papers-benchmarks" class="level3">
<h3 class="anchored" data-anchor-id="papers-benchmarks">Papers &amp; Benchmarks</h3>
<ul>
<li><strong>SWE-bench: Resolving Real-World GitHub Issues</strong> (Jimenez et al., 2023) — <a href="https://arxiv.org/abs/2310.06770">arXiv:2310.06770</a></li>
<li><strong>SWE-agent: Agent-Computer Interface Enables Automated Software Engineering</strong> (Yang et al., 2024, Princeton NLP) — <a href="https://arxiv.org/abs/2405.15793">arXiv:2405.15793</a></li>
<li><strong>Agentic AI: A Comprehensive Survey of Architectures, Applications, and Future Directions</strong> (Abou Ali &amp; Dornaika, 2025) — <a href="https://arxiv.org/abs/2510.25445">arXiv:2510.25445</a></li>
<li><strong>Agentic AI Frameworks: Architectures, Protocols, and Design Challenges</strong> (Derouiche et al., 2025) — <a href="https://arxiv.org/abs/2508.10146">arXiv:2508.10146</a></li>
<li><strong>Architectures for Building Agentic AI</strong> (2025) — <a href="https://arxiv.org/abs/2512.09458">arXiv:2512.09458</a></li>
<li><strong>AI Agents vs.&nbsp;Agentic AI: A Conceptual Taxonomy</strong> (2025) — <a href="https://arxiv.org/abs/2505.10468">arXiv:2505.10468</a></li>
<li><strong>Towards a Science of Scaling Agent Systems</strong> (Kim et al., 2025) — <a href="https://arxiv.org/abs/2512.08296">arXiv:2512.08296</a></li>
<li><strong>The 2025 AI Agent Index</strong> (2026) — <a href="https://arxiv.org/abs/2602.17753">arXiv:2602.17753</a></li>
<li><strong>AI Agent Systems: Architectures, Applications, and Evaluation</strong> (2026) — <a href="https://arxiv.org/abs/2601.01743">arXiv:2601.01743</a></li>
<li><strong>GLM-5: From Vibe Coding to Agentic Engineering</strong> (GLM-5-Team, Zhipu AI &amp; Tsinghua University, 2026) — <a href="https://arxiv.org/abs/2602.15763">arXiv:2602.15763</a></li>
<li><strong>From Mind to Machine: The Rise of Manus AI as a Fully Autonomous Digital Agent</strong> (Yang et al., 2025; independent academic overview) — <a href="https://arxiv.org/abs/2505.02024">arXiv:2505.02024</a></li>
</ul>
</section>
<section id="open-source-projects-frameworks" class="level3">
<h3 class="anchored" data-anchor-id="open-source-projects-frameworks">Open-Source Projects &amp; Frameworks</h3>
<ul>
<li><strong>SWE-agent</strong> — <a href="https://github.com/princeton-nlp/SWE-agent">GitHub: princeton-nlp/SWE-agent</a></li>
<li><strong>OpenHands</strong> (formerly OpenDevin) — <a href="https://github.com/All-Hands-AI/OpenHands">GitHub: All-Hands-AI/OpenHands</a></li>
<li><strong>browser-use</strong> — <a href="https://github.com/browser-use/browser-use">GitHub: browser-use/browser-use</a></li>
<li><strong>Skyvern</strong> — <a href="https://github.com/Skyvern-AI/skyvern">GitHub: Skyvern-AI/skyvern</a></li>
<li><strong>Aider</strong> — <a href="https://aider.chat">aider.chat</a> · <a href="https://github.com/paul-gauthier/aider">GitHub: paul-gauthier/aider</a></li>
<li><strong>Goose</strong> — <a href="https://github.com/block/goose">GitHub: block/goose</a></li>
<li><strong>LangGraph</strong> — <a href="https://github.com/langchain-ai/langgraph">GitHub: langchain-ai/langgraph</a></li>
<li><strong>Google ADK</strong> (Agent Development Kit) — <a href="https://google.github.io/adk-docs/">google.github.io/adk-docs</a> · <a href="https://github.com/google/adk-python">GitHub: google/adk-python</a></li>
</ul>
</section>
<section id="official-framework-protocol-documentation" class="level3">
<h3 class="anchored" data-anchor-id="official-framework-protocol-documentation">Official Framework &amp; Protocol Documentation</h3>
<ul>
<li><strong>Model Context Protocol (MCP)</strong> — <a href="https://modelcontextprotocol.io">modelcontextprotocol.io</a></li>
<li><strong>Agent2Agent Protocol (A2A)</strong> — <a href="https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/">developers.googleblog.com</a> · Donated to Linux Foundation Jun 2025</li>
<li><strong>Microsoft Agent Framework</strong> — <a href="https://azure.microsoft.com/en-us/blog/introducing-microsoft-agent-framework/">azure.microsoft.com/blog/introducing-microsoft-agent-framework</a></li>
<li><strong>Claude Agent SDK</strong> — <a href="https://www.anthropic.com/engineering/building-agents-with-the-claude-agent-sdk">anthropic.com/engineering/building-agents-with-the-claude-agent-sdk</a></li>
<li><strong>OpenAI Operator &amp; Deep Research</strong> — <a href="https://openai.com/index/introducing-operator/">Introducing Operator</a> · <a href="https://openai.com/index/introducing-deep-research/">Introducing Deep Research</a> · <a href="https://openai.com/index/introducing-chatgpt-agent/">Introducing ChatGPT Agent</a></li>
<li><strong>Anthropic Computer Use</strong> — <a href="https://www.anthropic.com/">anthropic.com</a></li>
<li><strong>GitHub Copilot Coding Agent</strong> — <a href="https://github.blog/news-insights/product-news/github-copilot-meet-the-new-coding-agent/">github.blog</a></li>
</ul>
</section>
<section id="key-blog-posts-practitioner-resources" class="level3">
<h3 class="anchored" data-anchor-id="key-blog-posts-practitioner-resources">Key Blog Posts &amp; Practitioner Resources</h3>
<ul>
<li><strong>Building Effective Agents</strong> (Erik Schluntz &amp; Barry Zhang, Anthropic, Dec 2024) — <a href="https://www.anthropic.com/research/building-effective-agents">anthropic.com/research/building-effective-agents</a>
<ul>
<li>Simon Willison’s summary: <a href="https://simonwillison.net/2024/Dec/20/building-effective-agents/">simonwillison.net/2024/Dec/20/building-effective-agents/</a></li>
</ul></li>
<li><strong>Reference Implementations for Agent Patterns</strong> (Anthropic Cookbook) — <a href="https://github.com/anthropics/anthropic-cookbook/tree/main/patterns/agents">github.com/anthropics/anthropic-cookbook</a></li>
<li><strong>Lessons from 2025 on Agents and Trust</strong> (Google Cloud CTO Office, Dec 2025) — <a href="https://cloud.google.com/transform/ai-grew-up-and-got-a-job-lessons-from-2025-on-agents-and-trust">cloud.google.com</a></li>
<li><strong>Agentic AI, MCP, and Spec-Driven Development</strong> (GitHub Blog, Jan 2026) — <a href="https://github.blog/developer-skills/agentic-ai-mcp-and-spec-driven-development-top-blog-posts-of-2025/">github.blog</a></li>
<li><strong>What We Learned from a Year of Building with LLMs</strong> (Eugene Yan et al., 2024) — <a href="https://applied-llms.org">applied-llms.org</a></li>
<li><strong>Model Context Protocol Overview</strong> (Simon Willison, Nov 2024) — <a href="https://simonwillison.net/2024/Nov/25/model-context-protocol/">simonwillison.net/2024/Nov/25/model-context-protocol/</a></li>
<li><strong>AI in Production: Frameworks, Protocols, and What Actually Works in 2026</strong> (47 Billion) — <a href="https://47billion.com/blog/ai-agents-in-production-frameworks-protocols-and-what-actually-works-in-2026/">47billion.com/blog/ai-agents-in-production-frameworks-protocols-and-what-actually-works-in-2026/</a></li>
<li><strong>Agents 101: How to Work with Coding Agents</strong> (Cognition AI) — <a href="https://devin.ai/agents101">devin.ai/agents101</a></li>
</ul>
</section>
<section id="enterprise-products-evaluations" class="level3">
<h3 class="anchored" data-anchor-id="enterprise-products-evaluations">Enterprise Products &amp; Evaluations</h3>
<ul>
<li><strong>MIT AI Agent Index</strong> (2025) — <a href="https://aiagentindex.mit.edu">aiagentindex.mit.edu</a>
<ul>
<li>Companion paper: <strong>The 2025 AI Agent Index</strong> (Staufer et al., 2026) — <a href="https://arxiv.org/abs/2602.17753">arXiv:2602.17753</a></li>
</ul></li>
<li><strong>Devin</strong> — <a href="https://cognition.ai">cognition.ai</a></li>
<li><strong>Manus AI</strong> — <a href="https://manus.im">manus.im</a></li>
<li><strong>Aider Coding Leaderboard</strong> — <a href="https://aider.chat/docs/leaderboards">aider.chat/docs/leaderboards</a></li>
</ul>
</section>
<section id="measurement-research" class="level3">
<h3 class="anchored" data-anchor-id="measurement-research">Measurement &amp; Research</h3>
<ul>
<li><strong>METR: Task Time Horizons as a Measure of Agent Capability</strong> (METR, 2025) — <a href="https://metr.org/time-horizons/">metr.org/time-horizons</a></li>
<li><strong>OpenAI Harness Engineering</strong> — <a href="https://openai.com/index/harness-engineering/">openai.com/index/harness-engineering</a></li>
<li><strong>Running Long-Horizon Tasks with Codex</strong> (OpenAI) — <a href="https://developers.openai.com/blog/run-long-horizon-tasks-with-codex">developers.openai.com/blog/run-long-horizon-tasks-with-codex</a></li>
</ul>
<p><em>Back to <a href="./index.html">Overview →</a> · See <a href="./resources.html">Resources →</a> for a curated reading list</em></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/johnplake\.github\.io\/llm-agents-survey\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>